#!/bin/bash
# SAML migration script for Sakai
# This script helps with migration from spring-security-saml-extension to Spring Security SAML 2.0

set -e

# Determine the Sakai home directory
if [ -z "$SAKAI_HOME" ]; then
  SAKAI_HOME="/opt/tomcat/sakai"
  echo "SAKAI_HOME not set, using default: $SAKAI_HOME"
fi

# Determine the Tomcat directory
if [ -z "$CATALINA_HOME" ] && [ -z "$CATALINA_BASE" ]; then
  # Try to guess from SAKAI_HOME
  TOMCAT_DIR=$(dirname "$SAKAI_HOME")
  echo "CATALINA_HOME and CATALINA_BASE not set, guessing: $TOMCAT_DIR"
else
  # Use CATALINA_BASE if set, otherwise CATALINA_HOME
  TOMCAT_DIR=${CATALINA_BASE:-$CATALINA_HOME}
  echo "Using Tomcat directory: $TOMCAT_DIR"
fi

# Create backup directory
BACKUP_DIR="$SAKAI_HOME/saml-backup-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$BACKUP_DIR"
echo "Created backup directory: $BACKUP_DIR"

# Create Tomcat SAML configuration directory
TOMCAT_SAML_DIR="$TOMCAT_DIR/sakai/saml"
mkdir -p "$TOMCAT_SAML_DIR"
echo "Created Tomcat SAML configuration directory: $TOMCAT_SAML_DIR"

# Backup existing SAML files
echo "Backing up existing SAML files..."
if [ -f "$SAKAI_HOME/SakaiSAMLApp_sp.xml" ]; then
  cp "$SAKAI_HOME/SakaiSAMLApp_sp.xml" "$BACKUP_DIR/"
  echo "Backed up SP metadata: $SAKAI_HOME/SakaiSAMLApp_sp.xml"
fi

if [ -f "$SAKAI_HOME/ssocircle_idp.xml" ]; then
  cp "$SAKAI_HOME/ssocircle_idp.xml" "$BACKUP_DIR/"
  echo "Backed up IdP metadata: $SAKAI_HOME/ssocircle_idp.xml"
fi

# Create sakai-saml.properties in Tomcat directory
echo "Creating sakai-saml.properties in Tomcat SAML directory..."
cat > "$TOMCAT_SAML_DIR/sakai-saml.properties" << EOL
# SAML Configuration Properties
# Generated by migrate-saml.sh on $(date)
# Located in Tomcat SAML directory: $TOMCAT_SAML_DIR

# Entity IDs
sakai.saml.sp.entityId=SakaiSAMLApp
sakai.saml.idp.entityId=http://idp.ssocircle.com

# Metadata paths
sakai.saml.sp.metadata.path=$TOMCAT_SAML_DIR/SakaiSAMLApp_sp.xml
sakai.saml.idp.metadata.path=$TOMCAT_SAML_DIR/ssocircle_idp.xml

# SAML Authentication Properties
sakai.saml.auth.useEppn=true
sakai.saml.auth.eppnAttributeName=urn:oid:1.3.6.1.4.1.5923.1.1.1.6
sakai.saml.auth.useUpn=true
sakai.saml.auth.upnAttributeName=http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn
sakai.saml.auth.defaultAttributeName=sub
sakai.saml.auth.appendAtSign=false
sakai.saml.auth.atSignDomain=

# Timeout settings (in seconds)
sakai.saml.maxAuthenticationAge=7200

# Logging settings
sakai.saml.verbose.logging=false

# URLs
sakai.saml.loginUrl=/container/saml/login
sakai.saml.logoutUrl=/container/saml/logout
sakai.saml.ssoUrl=/container/saml/SSO
sakai.saml.sloUrl=/container/saml/SingleLogout
sakai.saml.metadataUrl=/container/saml/metadata
EOL

echo "Created $TOMCAT_SAML_DIR/sakai-saml.properties"

# Also create a mocksaml properties file for testing
echo "Creating mocksaml configuration in Tomcat SAML directory..."
cat > "$TOMCAT_SAML_DIR/sakai-saml-mocksaml.properties" << EOL
# MockSaml Configuration for Testing
# Generated by migrate-saml.sh on $(date)
# Located in Tomcat SAML directory: $TOMCAT_SAML_DIR

# Enable MockSaml mode
sakai.saml.mock.enabled=true
sakai.saml.mock.baseUrl=http://localhost:8080/mocksaml
sakai.saml.verbose.logging=true

# Entity IDs
sakai.saml.sp.entityId=sakai-sp
sakai.saml.idp.entityId=mocksaml-idp

# Metadata URLs
sakai.saml.idp.metadata.url=${sakai.saml.mock.baseUrl}/metadata
sakai.saml.idp.sso.url=${sakai.saml.mock.baseUrl}/sso

# Mock user settings
sakai.saml.mock.username=testuser
EOL

echo "Created $TOMCAT_SAML_DIR/sakai-saml-mocksaml.properties"

# Check if Java is available for running the converter
if command -v java &> /dev/null; then
  echo "Java is available. You can run the MetadataConverter with:"
  echo "java -cp sakai-login-tool.jar org.sakaiproject.login.saml.MetadataConverter idp $SAKAI_HOME/ssocircle_idp.xml $SAKAI_HOME/ssocircle_idp_new.xml"
else
  echo "Java not found. Please manually convert the metadata files."
fi

echo ""
echo "Migration preparation complete!"
echo "Next steps:"
echo "1. Review and edit $SAKAI_HOME/sakai-saml.properties"
echo "2. Run the MetadataConverter if necessary"
echo "3. Test the new SAML configuration"
echo "4. Rename xlogin-context.saml-new.xml to xlogin-context.saml.xml after successful testing"
echo ""
echo "Backup of original files is located at: $BACKUP_DIR"