#!/bin/bash
# SAML migration script for Sakai
# This script helps with migration from spring-security-saml-extension to Spring Security SAML 2.0

set -e

# Determine the Sakai home directory
if [ -z "$SAKAI_HOME" ]; then
  SAKAI_HOME="/opt/tomcat/sakai"
  echo "SAKAI_HOME not set, using default: $SAKAI_HOME"
fi

# Create backup directory
BACKUP_DIR="$SAKAI_HOME/saml-backup-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$BACKUP_DIR"
echo "Created backup directory: $BACKUP_DIR"

# Backup existing SAML files
echo "Backing up existing SAML files..."
if [ -f "$SAKAI_HOME/SakaiSAMLApp_sp.xml" ]; then
  cp "$SAKAI_HOME/SakaiSAMLApp_sp.xml" "$BACKUP_DIR/"
  echo "Backed up SP metadata: $SAKAI_HOME/SakaiSAMLApp_sp.xml"
fi

if [ -f "$SAKAI_HOME/ssocircle_idp.xml" ]; then
  cp "$SAKAI_HOME/ssocircle_idp.xml" "$BACKUP_DIR/"
  echo "Backed up IdP metadata: $SAKAI_HOME/ssocircle_idp.xml"
fi

# Create sakai-saml.properties
echo "Creating sakai-saml.properties..."
cat > "$SAKAI_HOME/sakai-saml.properties" << EOL
# SAML Configuration Properties
# Generated by migrate-saml.sh on $(date)

# Entity IDs
sakai.saml.sp.entityId=SakaiSAMLApp
sakai.saml.idp.entityId=http://idp.ssocircle.com

# Metadata paths
sakai.saml.sp.metadata.path=$SAKAI_HOME/SakaiSAMLApp_sp.xml
sakai.saml.idp.metadata.path=$SAKAI_HOME/ssocircle_idp.xml

# SAML Authentication Properties
sakai.saml.auth.useEppn=true
sakai.saml.auth.eppnAttributeName=urn:oid:1.3.6.1.4.1.5923.1.1.1.6
sakai.saml.auth.useUpn=true
sakai.saml.auth.upnAttributeName=http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn
sakai.saml.auth.defaultAttributeName=sub
sakai.saml.auth.appendAtSign=false
sakai.saml.auth.atSignDomain=

# Timeout settings (in seconds)
sakai.saml.maxAuthenticationAge=7200

# Logging settings
sakai.saml.verbose.logging=false

# URLs
sakai.saml.loginUrl=/container/saml/login
sakai.saml.logoutUrl=/container/saml/logout
sakai.saml.ssoUrl=/container/saml/SSO
sakai.saml.sloUrl=/container/saml/SingleLogout
sakai.saml.metadataUrl=/container/saml/metadata
EOL

echo "Created $SAKAI_HOME/sakai-saml.properties"

# Check if Java is available for running the converter
if command -v java &> /dev/null; then
  echo "Java is available. You can run the MetadataConverter with:"
  echo "java -cp sakai-login-tool.jar org.sakaiproject.login.saml.MetadataConverter idp $SAKAI_HOME/ssocircle_idp.xml $SAKAI_HOME/ssocircle_idp_new.xml"
else
  echo "Java not found. Please manually convert the metadata files."
fi

echo ""
echo "Migration preparation complete!"
echo "Next steps:"
echo "1. Review and edit $SAKAI_HOME/sakai-saml.properties"
echo "2. Run the MetadataConverter if necessary"
echo "3. Test the new SAML configuration"
echo "4. Rename xlogin-context.saml-new.xml to xlogin-context.saml.xml after successful testing"
echo ""
echo "Backup of original files is located at: $BACKUP_DIR"