# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Build

on:
  pull_request:

jobs:
  maven-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6
      - name: Search for bad unicode translations
        run: |
          find . -name \*.properties -exec grep '\\u[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][^0-9a-fA-F]' {} \; &> grep.txt
          find . -name \*.properties -exec grep '\\u[0-9a-fA-F][0-9a-fA-F][^0-9a-fA-F][0-9a-fA-F]' {} \; &>> grep.txt
          find . -name \*.properties -exec grep '\\u[0-9a-fA-F][^0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]' {} \; &>> grep.txt
          find . -name \*.properties -exec grep '\\u[^0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]' {} \; &>> grep.txt
          if [ -s grep.txt ]; then
            exit 1
          fi
      - name: Build with Maven
        env:
          MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Dmaven.wagon.http.retryHandler.count=2 -Dmaven.wagon.http.pool=true
        run: mvn --show-version --batch-mode -PskipBrokenTests test
      - name: Test Web Components
        run: |
          for dir in webcomponents/tool/src/main/frontend/packages/*; do                                                                        ✔  42s  11:22:54 AM
            if [[ "$dir" == *"dashboard"* ]]; then
              echo "Skipping $dir"
              continue
            fi

            if [[ -f "$dir/package.json" ]]; then
              if jq -e '.scripts.test' "$dir/package.json" > /dev/null; then
                echo "Testing $dir"
                (cd "$dir" && npm run test -s)
              else
                echo "No test script found in $dir/package.json"
              fi
            fi
          done
#      - name: Check Licenses
#        run: mvn -show-version --batch-mode -DskipTests license:check


