# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  pull_request:
    branches: [ master, 19.x, 20.x, 21.x, 22.x, 23.x ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        jdk: [8]
        experimental: [false]
        include:
          - jdk: 11
            os: ubuntu-latest
            experimental: true
            name: Ubuntu JDK 11
          - jdk: 11
            os: windows-latest
            experimental: true
            name: Windows JDK 11
          - jdk: 11
            os: macos-latest
            experimental: true
            name: MacOS JDK 11
    env:
      JDK_VERSION:  ${{ matrix.jdk }}

    steps:
      # https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: JDK Setup
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
          architecture: x64
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        env:
          MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Dmaven.wagon.http.retryHandler.count=2 -Dmaven.wagon.http.pool=true
        run: mvn --batch-mode -PskipBrokenTests test
      - name: Report jUnit Annotations as Github Actions Annotations
        uses: shyim/junit-report-annotations-action@0.2.0
        with:
          path: '**/surefire-reports/*.xml'
